/*
 * alertmanager
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.PaginationSchema;
import org.openapitools.client.model.PolicyChannelSchema;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ChannelsApi
 */
@Disabled
public class ChannelsApiTest {

    private final ChannelsApi api = new ChannelsApi();

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deletePolicyChannelsDeleteTest() throws ApiException {
        String id = null;
        PolicyChannelSchema response = api.deletePolicyChannelsDelete(id);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getPolicyChannelsGetTest() throws ApiException {
        String id = null;
        PolicyChannelSchema response = api.getPolicyChannelsGet(id);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getPolicyChannelsGetAllTest() throws ApiException {
        PaginationSchema response = api.getPolicyChannelsGetAll();
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void postPolicyChannelsPostTest() throws ApiException {
        PolicyChannelSchema requestBody = null;
        PolicyChannelSchema response = api.postPolicyChannelsPost(requestBody);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void postPolicyChannelsTestTest() throws ApiException {
        PolicyChannelSchema requestBody = null;
        PolicyChannelSchema response = api.postPolicyChannelsTest(requestBody);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void putPolicyChannelsPutTest() throws ApiException {
        String id = null;
        PolicyChannelSchema requestBody = null;
        PolicyChannelSchema response = api.putPolicyChannelsPut(id, requestBody);
        // TODO: test validations
    }

}
