/*
 * alertmanager
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.ClientAppSchema;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DefaultApi
 */
@Disabled
public class DefaultApiTest {

    private final DefaultApi api = new DefaultApi();

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteClientAppGetDeleteTest() throws ApiException {
        String id = null;
        String response = api.deleteClientAppGetDelete(id);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getClientAppGetTest() throws ApiException {
        String id = null;
        ClientAppSchema response = api.getClientAppGet(id);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getClientAppGetAllTest() throws ApiException {
        List<ClientAppSchema> response = api.getClientAppGetAll();
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getDocsTest() throws ApiException {
        api.getDocs();
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getHealthCheckTest() throws ApiException {
        api.getHealthCheck();
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getSwaggerJsonTest() throws ApiException {
        api.getSwaggerJson();
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void postClientAppPostTest() throws ApiException {
        String id = null;
        ClientAppSchema requestBody = null;
        ClientAppSchema response = api.postClientAppPost(id, requestBody);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void putClientAppPutTest() throws ApiException {
        ClientAppSchema response = api.putClientAppPut();
        // TODO: test validations
    }

}
