/*
 * alertmanager
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.EventSchema;
import org.openapitools.client.model.PaginationSchema;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for EventsApi
 */
@Disabled
public class EventsApiTest {

    private final EventsApi api = new EventsApi();

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteEventsParametersDeleteTest() throws ApiException {
        String appKey = null;
        String response = api.deleteEventsParametersDelete(appKey);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getEventsGetTest() throws ApiException {
        String id = null;
        EventSchema response = api.getEventsGet(id);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getEventsGetAllTest() throws ApiException {
        PaginationSchema response = api.getEventsGetAll();
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getEventsParametersGetTest() throws ApiException {
        List<EventSchema> response = api.getEventsParametersGet();
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void postEventsPostTest() throws ApiException {
        EventSchema requestBody = null;
        EventSchema response = api.postEventsPost(requestBody);
        // TODO: test validations
    }

}
