/*
 * alertmanager
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.PaginationSchema;
import org.openapitools.client.model.PolicySchema;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PoliciesApi
 */
@Disabled
public class PoliciesApiTest {

    private final PoliciesApi api = new PoliciesApi();

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deletePoliciesDeleteTest() throws ApiException {
        String id = null;
        PolicySchema response = api.deletePoliciesDelete(id);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getPoliciesGetTest() throws ApiException {
        String id = null;
        PolicySchema response = api.getPoliciesGet(id);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getPoliciesGetAllTest() throws ApiException {
        PaginationSchema response = api.getPoliciesGetAll();
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void postPoliciesPostTest() throws ApiException {
        PolicySchema requestBody = null;
        PolicySchema response = api.postPoliciesPost(requestBody);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void putPoliciesPutTest() throws ApiException {
        String id = null;
        PolicySchema requestBody = null;
        PolicySchema response = api.putPoliciesPut(id, requestBody);
        // TODO: test validations
    }

}
