/*
 * alertmanager
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for WelcomeApi
 */
@Disabled
public class WelcomeApiTest {

    private final WelcomeApi api = new WelcomeApi();

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getWelcomeTest() throws ApiException {
        api.getWelcome();
        // TODO: test validations
    }

}
